### ISSUE TITLE
Tag request for GCHP

### ISSUE THREAD

**Issue by lizziel** [Goddard-Fortran-Ecosystem/GFE#8]
It would be useful to have a GFE tag with versions that will be included in the upcoming GCHP 14.0 release. Then we can swap out the submodules with GFE at any time. The versions we will be using are:

gFTL-shared: v1.4.1
gFTL: v1.6.0
pFlogger: v1.6.1
yaFyaml: v1.0-beta.4

This is the combination of the latest versions that I found work with MAPL 2.18.3. We currently do not use the other libraries in GFE so they can be any version. Would generating a tag with this set be possible?

**Comment by mathomp4** [comment]
@lizziel One more question. Would you be okay with using yaFyaml v1.0-beta5? The difference from beta4 to beta5 was:

- New interface to Parser::load() to allow a user to directly load a configuration from just a filename rather than being required to first construct a FileStream from the filename.

and this is the version of yaFyaml MAPL 2 is currently using. 

Note: I'm asking because it would allow me to make a nice Semantic Version progression the GFE releases. :)

**Comment by mathomp4** [comment]
@lizziel Just checking in to see you had any objection to using beta5 of yaFyaml?

**Comment by lizziel** [comment]
Sorry for the delay on getting back to you on this, I was on vacation. When I was testing with MAPL 2.18.3, which is what we are currently using GCHP dev, I could not get beta5 to work. I don't recall if the problem was incompatibility with MAPL or with pFlogger.

**Comment by mathomp4** [comment]
> Sorry for the delay on getting back to you on this, I was on vacation. When I was testing with MAPL 2.18.3, which is what we are currently using GCHP dev, I could not get beta5 to work. I don't recall if the problem was incompatibility with MAPL or with pFlogger.

Well, if it doesn't work, it doesn't work! It's only my sense of style that was "offended". I'll work on getting you something soon

**Comment by lizziel** [comment]
Thanks @mathomp4. Hopefully this will be the only "for GCHP" tag that we will need. In future versions there will always be at least one GFE tag compatible with each MAPL release, right?
